apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-webapp
  labels:
    app: spring-boot-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-webapp
  template:
    metadata:
      labels:
        app: spring-boot-webapp
    spec:
      containers:
      - name: spring-boot-webapp
        image: sumit0058/springbootwebapp:replaceTag
        ports:
        - containerPort: 8081
