apiVersion: v1
kind: Service
metadata:
  name: spring-boot-webapp-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app: spring-boot-webapp
